### ISSUE TITLE
Small security improvement: id parameters as PARAM_INT instead of PARAM_TEXT

### ISSUE THREAD

**Issue by tmuras** [adpe/moodle-local_rocketchat#3]
The courseid parameter in set_rocketchat_event_based_sync_parameters, set_rocketchat_event_based_sync_parameters, manually_trigger_sync_parameters 
and 
roleid in set_rocketchat_role_sync_parameters - all in externallib.php - could be set to PARAM_INT instead of PARAM_TEXT.

**Comment by adpe** [comment]
Thanks @tmuras 

I've further removed the `DEFAULT_VALUE` of the required option, as this field are mandatory, and default should not be really `null`.

Greets
Adrian
