### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by danmarsden** [adpe/moodle-local_rocketchat#4]
You have Moodle GPL headers in lots of places in your code and then state the licencse is MIT in phpdocs... 

Please note that all moodle plugin files must be GPL as per:
https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing

You can include 3rd party libaries (not based on Moodle code) under a different license within your plugin as mentioned in that doc, but the main Moodle plugin files need to be licesnsed under GPL.

note this is a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
don't forget to fix the LICENCSE file in the root of this repo too.

**Comment by adpe** [comment]
Thanks @danmarsden 

Fixed!
