### ISSUE TITLE
missing external_location_link in privacy api implementatoin

### ISSUE THREAD

**Issue by danmarsden** [adpe/moodle-local_rocketchat#5]
as your plugin exports private user information to an external service you need to include this information in the privacy class - more details here:

https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

Please note - this is a blocker for approval in the plugins db. - thanks!

**Comment by adpe** [comment]
Hi @danmarsden 

Can you maybe let me know what is missing? I've implemented some Privacy API stuff.

Greets
Adrian

**Comment by danmarsden** [comment]
it's pretty simple - you just need to add  $collection->add_external_location_link to your get_metadata function like in the example shown on :
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

Just make sure it includes all the information you send to the external service (username/email etc)
here's an example from a plagiarism plugin that just sends email/filename/file to an external service
https://github.com/danmarsden/moodle-plagiarism_urkund/blob/main/classes/privacy/provider.php#L60-L64

**Comment by adpe** [comment]
Thank you very much @danmarsden 

Fixed.
