### ISSUE TITLE
sync set to run at 1min past hour every hour

### ISSUE THREAD

**Issue by danmarsden** [adpe/moodle-local_rocketchat#7]
Lots of things run on the hour - moodle has a special value "R" that allows a random number to be used on install rather than setting a specific value - see: https://docs.moodle.org/dev/Task_API#Cron_syntax_examples for more info.

not a requirement - just a suggestion, feel free to close as won't fix.

**Comment by adpe** [comment]
Thanks, @danmarsden, for this suggestion and for learning something new to Moodle tasks defaults.

I've added it!
